import {
  imgParcele,
  videoParcele,
  imgWeather,
  videoWeather,
  videoALe,
  imgALe,
  imgFood,
  videoFood,
  imgThanos,
  videoThanos,
  videoPig,
  imgPig,
} from "../utils/utils";

export const projects = [
  {
    id: "Parcele",
    title: "Parcele aqui",
    subtitle: "Parcele seus boletos de forma simples e segura",
    description:
      "Site que ajudei fazendo o design e o frontend para parcelamento de boletos em até 12x com até 3 cartões, podendo parcelar até débitos veiculares",
    image: imgParcele,
    video: videoParcele,
    link: "https://www.parceleaqui.com.br/",
    year: "(2023) Fev - Nov",
    credits: [
      { name: "Potencial tecnologia", work: "Empresa" },
      { name: "Enzo Shiotuqui", work: "Dev FE" },
    ],
    services: ["Web Development", "Web Design", "Vue.js", "Nuxt.js"],
    git: "",
    pitch: videoParcele,
  },
  {
    id: "Weather",
    title: "Weather.io",
    subtitle: "Veje informações sobre o clima de qualquer lugar do mundo!",
    description:
      "Dashboard weather.io que utiliza a API OpenWeather, mostra clima do local que quiser, mostrando previsão de 5 dias, temperatura durante o dia e muito mais!",
    image: imgWeather,
    video: videoWeather,
    link: "https://eweatherio.netlify.app/#/current-location",
    year: "(2024) Mai - Jun",
    credits: [{ name: "Enzo Shiotuqui", work: "Dev" }],
    services: ["Web Development", "Web Design", "HTML", "JS", "CSS"],
    git: "https://github.com/Eshiotuqui/weatherApp",
    pitch: videoWeather,
  },
  {
    id: "Ale",
    title: "Ale school",
    subtitle: "Controle sua escola com uma plataforma simples e intuitiva",
    description:
      "Uma plataforma com intuido de ajudar professores, coordenadores a gerenciar, cadastrar e ver informações sobre seus alunos, escolas, tarefas e muito mais! Além de possuir uma plataforma para alunos acessarem, verem aulas cadastradas e fazerem suas tarefas",
    image: imgALe,
    video: videoALe,
    link: "",
    year: "(2025) Jan - Mai",
    credits: [
      { name: "Nexus", work: "Empresa" },
      { name: "Enzo Shiotuqui", work: "Dev" },
    ],
    services: ["Web Development", "Web Design", "React", "TS"],
    git: "",
    pitch: videoALe,
  },
  {
    id: "Food",
    title: "Food Theme",
    subtitle: "Landing Page para restaurante",
    description:
      "Landing page para uma prova que fiz para a faculdade, misturando html, css e js junto a animação, foi um dos primeiro projetos que fiz com as tecnologias front-end",
    image: imgFood,
    video: videoFood,
    link: "https://foodtheme.netlify.app/",
    year: "(2024) Nov - Dez",
    credits: [{ name: "Enzo Shiotuqui", work: "Dev FE" }],
    services: ["Web Development", "Web Design", "HTML", "CSS"],
    git: "https://github.com/Eshiotuqui/Food-Theme",
    pitch: videoFood,
  },
  {
    id: "Thanos",
    title: "Thanos Store",
    subtitle: "Landing Page loja de tênis",
    description:
      "Landing page para uma loja de tênis. A tela possui carrosel, tela de checkout de pagamento, escolha de cor e muito mais.",
    image: imgThanos,
    video: videoThanos,
    link: "https://thanosstore.netlify.app/",
    year: "(2022) Ago - Set",
    credits: [{ name: "Enzo Shiotuqui", work: "Dev FE" }],
    services: ["Web Development", "Web Design", "React", "JS"],
    git: "https://github.com/Eshiotuqui/Sneakers_Shop",
    pitch: videoThanos,
  },
  {
    id: "Piglet",
    title: "PigLet",
    subtitle: "Leitão procurador de tudo na wiki",
    description:
      "Site que fiz de um facilitador de pesquisa na wiki, o piglet precisa apenas de 1 palavra para achar diversos assuntos na wiki",
    image: imgPig,
    video: videoPig,
    link: "https://foodtheme.netlify.app/",
    year: "(2023) Nov - Dez",
    credits: [{ name: "Enzo Shiotuqui", work: "Dev FE" }],
    services: ["Web Development", "Web Design", "HTML", "CSS", "JS"],
    git: "https://github.com/Eshiotuqui/Food-Theme",
    pitch: videoPig,
  },
];
